version: '3'
services:
 db:
   image: mariadb
   volumes:
     - "./dev/data/db:/var/lib/mysql"
   ports:
     - "4502:3306"
   environment:
     MYSQL_ROOT_PASSWORD: secreto
     MYSQL_DATABASE: dbEjemplo
     MYSQL_USER: root
     MYSQL_PASSWORD: secreto

 apache:
   image: webdevops/php-apache-dev:alpine-3-php7
   depends_on:
     - db
   volumes:
     - ".:/web"
   ports:
     - "80:80"
   environment:
     WEB_DOCUMENT_ROOT: /web
